# configfile for triplet_loss dir: 
hypersearch: False

numb_classes: 10
#training settings:
# batch_size: [64, 128, 256]
batch_size: 64
test_batch_size: 1000
epoch: 1
# learning_rate: [1,0.1,0.001]
learning_rate: 1.0
# learningrate step gamma: 
gamma: 0.7
cuda: True
#random seed
seed: 42
# wait nmbr of batches befor logging
log_interval: 10
save_model: True


# path to dataset:
path_dataset: "../../datasets"

train_net: True

# whenn in test mode, test for a batch or test for sigle image
test_batch: True